### ISSUE TITLE
AccessTokens should not have an empty list of scopes

### ISSUE THREAD

**Issue by rtisma** [overture-stack/ego#363]
If an access token contains only one scope, and the policy associated with that scope is deleted, the CleanupTokenListener will remove the scope from the token, however the token will still exist with an empty list of scopes.

Since its only possible to remove scopes from a token and not add them, there is no use for a token with no scopes, therefore it should be deleted

This change would involve additional logic to the CleanupTokenListener and a test

**Comment by andricDu** [comment]
@Buwujiu first verify the issue and see if you can reproduce. CleanupTokenListener should be deleting the token already. If it's not then we have a bug.

**Comment by Buwujiu** [comment]
Verified in QA, the issue no longer exists. After deleting the policy, access token is revoked, refer to the screenshot below you can see that `checkToken` endpoint indicates that token has expired.
![image.png](https://images.zenhubusercontent.com/5c9a3377f234b2000189633c/c918855a-0b3c-4075-ba24-16f5340c3a97)

Steps performed to verify:
where: Ego qa
1. create a test user test@example.com
2. create a test policy TEST-POLICY
3. add permission to user, and check user scope with `/o/scopes`: 
```
{
  "scopes": [
    "TEST-POLICY.READ"
  ]
}
```
4. issue a token to test user using `issueToken` endpoint: 
```
{
  "accessToken": "56a625ed-8125-44e7-a39d-5cd0d5182508",
  "scope": [
    "TEST-POLICY.READ"
  ],
  "exp": 31536000,
  "description": null
}
```
5. delete policy `TEST-POLICY`
6. verify if the single scope token is still valid using `checkToken` endpoint, response is: 
```{"error": "Token \"56a625ed-8125-44e7-a39d-5cd0d5182508\" has expired or is no longer valid. "}```

Which is expected behaviour as tokens with empty scope should be revoked.

**Comment by Buwujiu** [comment]
@rosibaj Could you please test this in QA? Thanks!
