### ISSUE TITLE
Define technical architecture of Ego Refresh Tokens 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/ego#414]
- Define how to manage refresh tokens on the server.  
- Consider: 
--- creation 
--- persistence 
--- resolution
--- revocation 

## Exit Criteria 
Architecture is determined here
https://wiki.oicr.on.ca/display/DCCSOFT/Fall+2019%3A+Ego+Updates+to+manage+Permissions#Fall2019:EgoUpdatestomanagePermissions-3.1.3TechnicalImplementationSpecs

**Comment by anncatton** [comment]
From what I found online, tracking refresh tokens in a db seems to be an accepted way to manage them, with or without jwt access tokens. 

https://github.com/googleapis/google-api-nodejs-client/issues/853
https://api.slack.com/docs/oauth-safety
https://stackoverflow.com/questions/31919067/how-can-i-revoke-a-jwt-token
https://fusionauth.io/blog/2019/01/31/revoking-jwts

I think it's a good option:
- it's simple
- it allows us to easily revoke refresh tokens if necessary
- i think we can store a minimal amount of info to track tokens, expiry times and applicable access tokens
- we only need to store the latest refresh token
- i think it should be easily scalable

Using another jwt for the refresh token (or the jwt-within-jwt :) ) might be more problematic because of the size constraints of what we can pass in the request?
Also if i'm understanding jwts correctly, they could be harder to revoke if needed
